export const DEFAULT_CATEGORIES = [
  { name: 'Sueldo', type: 'income' as const, icon: '💼', color: '#4CAF50' },
  { name: 'Freelance', type: 'income' as const, icon: '💻', color: '#8BC34A' },
  { name: 'Inversiones', type: 'income' as const, icon: '📈', color: '#00BCD4' },
  { name: 'Regalos', type: 'income' as const, icon: '🎁', color: '#E91E63' },
  { name: 'Reembolsos', type: 'income' as const, icon: '🔄', color: '#FF9800' },
  { name: 'Otros ingresos', type: 'income' as const, icon: '📋', color: '#9E9E9E' },
  { name: 'Servicios', type: 'expense' as const, icon: '💡', color: '#FF5722' },
  { name: 'Transporte', type: 'expense' as const, icon: '🚗', color: '#2196F3' },
  { name: 'Alimentación', type: 'expense' as const, icon: '🍔', color: '#4CAF50' },
  { name: 'Mercado', type: 'expense' as const, icon: '🛒', color: '#8BC34A' },
  { name: 'Restaurantes', type: 'expense' as const, icon: '🍽️', color: '#FF9800' },
  { name: 'Entretenimiento', type: 'expense' as const, icon: '🎬', color: '#9C27B0' },
  { name: 'Suscripciones', type: 'expense' as const, icon: '📱', color: '#3F51B5' },
  { name: 'Salud', type: 'expense' as const, icon: '🏥', color: '#F44336' },
  { name: 'Educación', type: 'expense' as const, icon: '📚', color: '#006064' },
  { name: 'Ropa', type: 'expense' as const, icon: '👕', color: '#E91E63' },
  { name: 'Hogar', type: 'expense' as const, icon: '🏠', color: '#795548' },
  { name: 'Donación', type: 'expense' as const, icon: '❤️', color: '#E91E63' },
  { name: 'Diezmo', type: 'expense' as const, icon: '🙏', color: '#004D40' },
  { name: 'Otros gastos', type: 'expense' as const, icon: '📋', color: '#607D8B' },
];
